<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150527181617 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_group (persistence_object_identifier VARCHAR(40) NOT NULL, server VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX IDX_55163C2A5A6DD5F6 (server), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_project (persistence_object_identifier VARCHAR(40) NOT NULL, projectgroup VARCHAR(40) DEFAULT NULL, server VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX IDX_A88BFE15974FCC6 (projectgroup), INDEX IDX_A88BFE155A6DD5F6 (server), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_project_issue (persistence_object_identifier VARCHAR(40) NOT NULL, project VARCHAR(40) DEFAULT NULL, milestone VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, INDEX IDX_D1B98F542FB3D0EE (project), INDEX IDX_D1B98F544FAC8382 (milestone), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_project_issue_comment (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_project_milestone (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_project_tag (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_server (persistence_object_identifier VARCHAR(40) NOT NULL, serveridentifier VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_group ADD CONSTRAINT FK_55163C2A5A6DD5F6 FOREIGN KEY (server) REFERENCES kaystrobach_gitlab_domain_model_server (persistence_object_identifier)");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project ADD CONSTRAINT FK_A88BFE15974FCC6 FOREIGN KEY (projectgroup) REFERENCES kaystrobach_gitlab_domain_model_group (persistence_object_identifier)");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project ADD CONSTRAINT FK_A88BFE155A6DD5F6 FOREIGN KEY (server) REFERENCES kaystrobach_gitlab_domain_model_server (persistence_object_identifier)");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_issue ADD CONSTRAINT FK_D1B98F542FB3D0EE FOREIGN KEY (project) REFERENCES kaystrobach_gitlab_domain_model_project (persistence_object_identifier)");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_issue ADD CONSTRAINT FK_D1B98F544FAC8382 FOREIGN KEY (milestone) REFERENCES kaystrobach_gitlab_domain_model_project_milestone (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project DROP FOREIGN KEY FK_A88BFE15974FCC6");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_issue DROP FOREIGN KEY FK_D1B98F542FB3D0EE");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_issue DROP FOREIGN KEY FK_D1B98F544FAC8382");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_group DROP FOREIGN KEY FK_55163C2A5A6DD5F6");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project DROP FOREIGN KEY FK_A88BFE155A6DD5F6");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_group");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_project");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_project_issue");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_project_issue_comment");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_project_milestone");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_project_tag");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_server");
	}
}