<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150528104910 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE kaystrobach_gitlab_domain_model_project_milestone_state (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone ADD state VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone ADD CONSTRAINT FK_E79674BEA393D2FB FOREIGN KEY (state) REFERENCES kaystrobach_gitlab_domain_model_project_milestone_state (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_E79674BEA393D2FB ON kaystrobach_gitlab_domain_model_project_milestone (state)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone DROP FOREIGN KEY FK_E79674BEA393D2FB");
		$this->addSql("DROP TABLE kaystrobach_gitlab_domain_model_project_milestone_state");
		$this->addSql("DROP INDEX IDX_E79674BEA393D2FB ON kaystrobach_gitlab_domain_model_project_milestone");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone DROP state");
	}
}