<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150528103132 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone ADD project VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone ADD CONSTRAINT FK_E79674BE2FB3D0EE FOREIGN KEY (project) REFERENCES kaystrobach_gitlab_domain_model_project (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_E79674BE2FB3D0EE ON kaystrobach_gitlab_domain_model_project_milestone (project)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone DROP FOREIGN KEY FK_E79674BE2FB3D0EE");
		$this->addSql("DROP INDEX IDX_E79674BE2FB3D0EE ON kaystrobach_gitlab_domain_model_project_milestone");
		$this->addSql("ALTER TABLE kaystrobach_gitlab_domain_model_project_milestone DROP project");
	}
}